export type CalendarDeadline = {
  id: string;
  title: string;
  dateISO: string;
  notes?: string;
  sourceSnippet?: string;
};

const SAFETY_FOOTER =
  "Generated by Deadline & Renewal Extractor - verify against the original document.";
const MAX_GOOGLE_DETAILS_LENGTH = 700;

function pad2(value: number) {
  return String(value).padStart(2, "0");
}

function parseIsoDate(isoDate: string) {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(String(isoDate || "").trim());
  if (!match) return null;
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const dt = new Date(Date.UTC(year, month - 1, day));
  if (
    Number.isNaN(dt.getTime()) ||
    dt.getUTCFullYear() !== year ||
    dt.getUTCMonth() + 1 !== month ||
    dt.getUTCDate() !== day
  ) {
    return null;
  }
  return dt;
}

function formatGoogleDatePart(dt: Date) {
  return `${dt.getUTCFullYear()}${pad2(dt.getUTCMonth() + 1)}${pad2(dt.getUTCDate())}`;
}

function addDaysUtc(dt: Date, days: number) {
  const next = new Date(dt.getTime());
  next.setUTCDate(next.getUTCDate() + days);
  return next;
}

function sanitizeTitleToken(value: string) {
  return (
    String(value || "")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "deadline"
  );
}

function hashStable(value: string) {
  let hash = 5381;
  for (let i = 0; i < value.length; i += 1) {
    hash = (hash * 33) ^ value.charCodeAt(i);
  }
  return (hash >>> 0).toString(16);
}

function toIcsDate(dateISO: string) {
  const dt = parseIsoDate(dateISO);
  if (!dt) return null;
  return formatGoogleDatePart(dt);
}

function escapeIcsText(value: string) {
  return String(value || "")
    .replace(/\\/g, "\\\\")
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .replace(/\n/g, "\\n")
    .replace(/,/g, "\\,")
    .replace(/;/g, "\\;");
}

function buildDescription(event: CalendarDeadline, maxLen?: number) {
  const parts = [];
  if (event.notes) parts.push(String(event.notes).trim());
  if (event.sourceSnippet) parts.push(`Source: ${String(event.sourceSnippet).trim()}`);
  parts.push(SAFETY_FOOTER);
  const raw = parts.filter(Boolean).join("\n\n").trim();
  if (!maxLen || raw.length <= maxLen) return raw;
  return `${raw.slice(0, Math.max(0, maxLen - 1)).trimEnd()}...`;
}

function utcTimestampNow() {
  const now = new Date();
  return (
    `${now.getUTCFullYear()}${pad2(now.getUTCMonth() + 1)}${pad2(now.getUTCDate())}` +
    `T${pad2(now.getUTCHours())}${pad2(now.getUTCMinutes())}${pad2(now.getUTCSeconds())}Z`
  );
}

function buildEventLines(event: CalendarDeadline, dtStamp: string) {
  const start = parseIsoDate(event.dateISO);
  if (!start) return null;
  const end = addDaysUtc(start, 1);
  const uid = `${hashStable(`${event.id}|${event.dateISO}|${event.title}`)}@deadline-renew-extractor`;
  const description = buildDescription(event);

  return [
    "BEGIN:VEVENT",
    `UID:${escapeIcsText(uid)}`,
    `DTSTAMP:${dtStamp}`,
    `DTSTART;VALUE=DATE:${formatGoogleDatePart(start)}`,
    `DTEND;VALUE=DATE:${formatGoogleDatePart(end)}`,
    `SUMMARY:${escapeIcsText(event.title)}`,
    `DESCRIPTION:${escapeIcsText(description)}`,
    "END:VEVENT"
  ];
}

export function buildGoogleCalendarUrl(event: CalendarDeadline) {
  const start = parseIsoDate(event.dateISO);
  if (!start) return null;
  const end = addDaysUtc(start, 1);
  const details = buildDescription(event, MAX_GOOGLE_DETAILS_LENGTH);
  const url = new URL("https://calendar.google.com/calendar/render");
  url.searchParams.set("action", "TEMPLATE");
  url.searchParams.set("text", event.title);
  url.searchParams.set("dates", `${formatGoogleDatePart(start)}/${formatGoogleDatePart(end)}`);
  url.searchParams.set("details", details);
  return url.toString();
}

export function buildDeadlineIcsFilename(event: CalendarDeadline) {
  const datePart = toIcsDate(event.dateISO);
  const prettyDate = datePart ? `${datePart.slice(0, 4)}-${datePart.slice(4, 6)}-${datePart.slice(6, 8)}` : "unknown-date";
  return `deadline-${prettyDate}-${sanitizeTitleToken(event.title)}.ics`;
}

export function buildIcsCalendar(events: CalendarDeadline[]) {
  const dtStamp = utcTimestampNow();
  const lines = ["BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//Deadline Renewal Extractor//EN", "CALSCALE:GREGORIAN"];
  for (const event of events) {
    const eventLines = buildEventLines(event, dtStamp);
    if (!eventLines) continue;
    lines.push(...eventLines);
  }
  lines.push("END:VCALENDAR");
  return `${lines.join("\r\n")}\r\n`;
}

export function triggerIcsDownload(filename: string, icsContent: string) {
  const blob = new Blob([icsContent], { type: "text/calendar;charset=utf-8" });
  const href = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = href;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(href);
}
